on:
  push:
    paths:
      - 'cpp/**'
  pull_request:
    paths:
      - 'cpp/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build C++ code
        working-directory: cpp
        run: |
          cmake --preset=default
          cd build/release && make

      - name: Test JL code
        working-directory: cpp/build/release
        run: make test
